spring:
  application:
    name: orn-ai

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ornai}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: 3600000
